## Data for Gree (SZ000651)

In [1]:
import tushare as ts
import pandas as pd
import numpy as np

In [2]:
ts.set_token('e232c0694c3e1093015836501024ba38614eef802b5a3645baae15c6')
pro = ts.pro_api()

### General Data

In [3]:
df = ts.pro_bar(ts_code='000651.SZ', start_date='20000101', end_date='20191231', adj='qfq')
df['trade_date'] = pd.to_datetime(df['trade_date'])
df.set_index('trade_date', inplace=True)
df = df.iloc[::-1]  # reverse

In [4]:
df

,ts_code,open,high,low,close,pre_close,change,pct_chg,vol,amount
trade_date,,,,,,,,,,
2002-09-06,000651.SZ,0.3895,0.3913,0.3854,0.3867,0.3895,-0.0028,-0.7189,2439.63,2.064837e+03
2002-09-09,000651.SZ,0.3849,0.3904,0.3826,0.3895,0.3867,0.0028,0.7241,3831.86,3.224324e+03
2002-09-10,000651.SZ,0.3895,0.3945,0.3877,0.3945,0.3895,0.0050,1.2837,2812.72,2.396429e+03
2002-09-11,000651.SZ,0.3936,0.3936,0.3872,0.3895,0.3945,-0.0050,-1.2674,2774.00,2.358549e+03
2002-09-12,000651.SZ,0.3886,0.3941,0.3863,0.3936,0.3895,0.0041,1.0526,3032.54,2.585185e+03
...,...,...,...,...,...,...,...,...,...,...
2019-12-25,000651.SZ,65.0000,65.1900,64.1500,64.4000,65.0200,-0.6200,-0.9536,198372.40,1.283338e+06
2019-12-26,000651.SZ,64.4600,64.8000,64.2500,64.7800,64.4000,0.3800,0.5901,165339.53,1.066133e+06
2019-12-27,000651.SZ,65.1500,65.7600,64.4000,64.5300,64.7800,-0.2500,-0.3859,249793.35,1.624183e+06
2019-12-30,000651.SZ,64.5700,65.7000,64.0500,65.5800,64.5300,1.0500,1.6272,264579.81,1.724507e+06
2019-12-31,000651.SZ,65.3500,65.8600,64.8000,65.5800,65.5800,0.0000,0.0000,209307.99,1.366603e+06

In [5]:
price = df[['open', 'close', 'low', 'high']]

In [6]:
price[-10:]

             open  close    low   high
trade_date
2019-12-18  64.39  64.37  64.12  66.10
2019-12-19  64.65  65.00  64.41  65.50
2019-12-20  64.99  64.51  64.33  65.42
2019-12-23  65.07  64.50  64.50  65.60
2019-12-24  64.93  65.02  64.66  65.49
2019-12-25  65.00  64.40  64.15  65.19
2019-12-26  64.46  64.78  64.25  64.80
2019-12-27  65.15  64.53  64.40  65.76
2019-12-30  64.57  65.58  64.05  65.70
2019-12-31  65.35  65.58  64.80  65.86

#### Daily Data

__Price__

In [7]:
daily = price.values.tolist()

In [8]:
daily[-10:]

[[64.39, 64.37, 64.12, 66.1],
 [64.65, 65.0, 64.41, 65.5],
 [64.99, 64.51, 64.33, 65.42],
 [65.07, 64.5, 64.5, 65.6],
 [64.93, 65.02, 64.66, 65.49],
 [65.0, 64.4, 64.15, 65.19],
 [64.46, 64.78, 64.25, 64.8],
 [65.15, 64.53, 64.4, 65.76],
 [64.57, 65.58, 64.05, 65.7],
 [65.35, 65.58, 64.8, 65.86]]

__MA Data__

In [9]:
ma = df.close.rolling(window=60).mean().round(2).tolist()

In [10]:
ma[-10:]

[59.68, 59.8, 59.9, 60.01, 60.13, 60.23, 60.35, 60.46, 60.61, 60.75]

__Date__

In [11]:
date = df.index.strftime('%F').tolist()

In [12]:
date[-10:]

['2019-12-18',
 '2019-12-19',
 '2019-12-20',
 '2019-12-23',
 '2019-12-24',
 '2019-12-25',
 '2019-12-26',
 '2019-12-27',
 '2019-12-30',
 '2019-12-31']

#### Monthly Data

__Price__

In [13]:
monthly = price.resample('BM').first().round(2)
monthly['close'] = price['close'].resample('BM').last().round(2)
monthly['high'] = price['high'].resample('BM').max().round(2)
monthly['low'] = price['low'].resample('BM').min().round(2)
monthly = monthly.dropna(axis=0)  # Drop NaN

In [14]:
monthly[-10:]

             open  close    low   high
trade_date
2019-03-29  43.88  45.87  43.01  47.06
2019-04-30  50.46  54.01  50.46  63.55
2019-05-31  51.87  50.83  49.09  54.98
2019-06-28  51.22  53.44  48.98  53.93
2019-07-31  54.65  53.53  52.01  57.33
2019-08-30  53.44  55.50  49.05  55.99
2019-09-30  56.95  57.30  56.36  60.56
2019-10-31  57.50  58.70  56.04  60.39
2019-11-29  59.00  57.71  56.20  65.16
2019-12-31  60.00  65.58  59.20  66.10

#### Quarterly Data

In [15]:
quarterly = price.resample('BQ').first().round(2)
quarterly['close'] = price['close'].resample('BQ').last().round(2)
quarterly['high'] = price['high'].resample('BQ').max().round(2)
quarterly['low'] = price['low'].resample('BQ').min().round(2)
quarterly = quarterly.dropna(axis=0)  # Drop NaN

In [16]:
quarterly[-10:]

             open  close    low   high
trade_date
2017-09-29  37.81  36.34  34.92  40.07
2017-12-29  36.91  41.90  36.45  46.20
2018-03-30  42.38  44.96  42.36  56.28
2018-06-29  44.71  45.20  42.26  48.95
2018-09-28  45.06  38.54  34.13  45.25
2018-12-31  37.15  34.22  33.89  39.08
2019-03-29  34.95  45.87  34.09  47.06
2019-06-28  50.46  53.44  48.98  63.55
2019-09-30  54.65  57.30  49.05  60.56
2019-12-31  57.50  65.58  56.04  66.10

#### Financial Data

In [17]:
fi = pro.balancesheet(ts_code='000651.SZ', start_date='20000101', end_date='20191231', \
                      fields='end_date,total_hldr_eqy_exc_min_int')

In [18]:
fi = fi.rename(columns={'total_hldr_eqy_exc_min_int': 'equity'})

In [19]:
fi = fi[1:70].iloc[::-1].round(2)

In [20]:
fi

    end_date        equity
69  20020930  1.994917e+09
68  20021231  1.835288e+09
67  20030331  1.905635e+09
66  20030630  2.021638e+09
65  20030930  2.133566e+09
..       ...           ...
5   20180930  8.668540e+10
4   20181231  9.132710e+10
3   20190331  9.348999e+10
2   20190630  9.244169e+10
1   20190930  1.007924e+11

[69 rows x 2 columns]

In [21]:
fi['bps'] = fi['equity'].apply(lambda x: x/6.016e9, 2)

In [22]:
fi[-10:]

    end_date        equity        bps
10  20170630  5.245822e+10   8.719783
9   20170930  5.862390e+10   9.744664
8   20171231  6.559501e+10  10.903425
7   20180331  7.092090e+10  11.788714
6   20180630  7.832354e+10  13.019205
5   20180930  8.668540e+10  14.409142
4   20181231  9.132710e+10  15.180701
3   20190331  9.348999e+10  15.540225
2   20190630  9.244169e+10  15.365972
1   20190930  1.007924e+11  16.754048

In [23]:
smt_bps = fi.bps.rolling(window=4).mean().tolist()

In [24]:
smt_bps = [round(x*3, 2) for x in smt_bps]
smt_bps[-10:]

[26.67, 27.78, 29.24, 30.87, 34.09, 37.59, 40.8, 43.61, 45.37, 47.13]

### Candlestick

__Price__

In [25]:
from pyecharts import options as opts
from pyecharts.charts import Kline
from pyecharts.charts import Line

In [26]:
len(quarterly)

69

In [27]:
ma = quarterly.close.rolling(window=10).mean().round(2).tolist()

In [28]:
def kline() -> Kline:
    kline = (
        Kline()
        .add_xaxis(quarterly.index.strftime('%F').tolist())
        .add_yaxis(
            'Kline',
            quarterly.values.tolist(),
            itemstyle_opts=opts.ItemStyleOpts(
                color='#DD2200',
                color0='#009933',
                border_color='#DD2200',
                border_color0='#009933',
            ),
        )
        .set_global_opts(
            xaxis_opts=opts.AxisOpts(is_scale=True),
            yaxis_opts=opts.AxisOpts(
                is_scale=True,
                splitarea_opts=opts.SplitAreaOpts(
                    is_show=True, areastyle_opts=opts.AreaStyleOpts(opacity=1)
                ),
            ),
            # Set Legend
            legend_opts=opts.LegendOpts(pos_right=90),
            # Set DataZoom
            datazoom_opts=[opts.DataZoomOpts(type_='inside', range_start=40, range_end=100), opts.DataZoomOpts()],
            # Set Title
            title_opts=opts.TitleOpts(title='æ ¼åŠ›ç”µå™¨-000651.SZ', pos_left=80),
            # Set Tooltip 
            tooltip_opts=opts.TooltipOpts(
                trigger='axis',
                axis_pointer_type='cross',
                background_color='rgba(245, 245, 245, 0.8)',
                border_width=1,
                border_color='#ccc',
                textstyle_opts=opts.TextStyleOpts(color='#000'),
            ),
            # Set Axispointer
            axispointer_opts=opts.AxisPointerOpts(
                is_show=True,
                link=[{'xAxisIndex': 'all'}],
                label=opts.LabelOpts(background_color='#777'),
            )
        )
    )
    MAline = (
        Line()
        .add_xaxis(quarterly.index.strftime('%F').tolist())
        .add_yaxis(
            series_name='MA10',
            y_axis=ma,
            itemstyle_opts=opts.ItemStyleOpts(color='#2F4F4F'),
            is_symbol_show=False,
            is_smooth=True,
            is_hover_animation=False,
            linestyle_opts=opts.LineStyleOpts(width=2, opacity=0.7),
            label_opts=opts.LabelOpts(is_show=False),
        )
        .set_global_opts(xaxis_opts=opts.AxisOpts(type_='category'))
    )
    return kline.overlap(MAline)

In [29]:
chart = kline()
chart.render_notebook()